version: "3.8"

services:
  # Cấu hình MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: htql_mysql
    restart: always
    environment:
      MYSQL_DATABASE: htql_thi
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # (Tùy chọn) Cấu hình Adminer - Công cụ xem Database trên web giống phpMyAdmin
  adminer:
    image: adminer
    container_name: htql_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db

volumes:
  db_data: # Lưu trữ dữ liệu vật lý để không bị mất khi tắt Docker
